### PR TITLE
Dont import authors but display them though!

### PR DESCRIPTION
**Pull request by benjaoming**
Fixes https://github.com/migcontrol/django-migcontrol/issues/180

### CODE REVIEW

**Comment by benjaoming** [comment]
@shavek this means that you can add authors and they will be displayed. But I deleted all currently imported author data because it was just random Wordpress stuff.

**Comment by shavek** [comment]
@benjaoming hey, I just tried to add my name to the "author" field of  my "Wagtail Manual" Wiki but it is not displayed... Am I doing something wrong?

**Comment by shavek** [comment]
https://migcontrol.overtag.dk/en/wiki/website-manual/
grafik

grafik

**Comment by benjaoming** [comment]
there was a little glitch in automatically updating the site, but it's fixed now :+1:

**Pull request merged**
